### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by andersy005** [NCAR/xdevbot-testing#4]
Registering/unregistering the following repositories:

- /add-repo repo:NCAR/integral campaign:analysis
- Bar
- /add-repo repo:NCAR/jupyterlab-pbs campaign:platform
- /add-repo repo:NCAR/testing-repo campaign:test

- /remove-repo repo:dask/dask campaign:analysis

- /add-repo repo:NCAR/xdevbot-testing campaign:core

- Bar /add-repo repo:NCAR/test campaign:core
- /remove-repo repo:NCAR/jupyterlab-pbs campaign:platform
- /remove-repo repo: campaign:platform

- /add-repo repo:NCAR/xdevbot-test campaign:core

**Comment by andersy005** [comment]
@kmpaul,


Here's the latest version (which includes the `/remove-repo` command. Let me know what you think.

**Comment by andersy005** [comment]
@kmpaul, what are your thoughts on the new "errors" section above?

**Comment by kmpaul** [comment]
These are great!  Thanks for doing this, @andersy005!

I might suggest that if you are planning of writing *text* error messages, then I think you should format the error message content to be proper (readable) text.

For example, instead of just printing a list as the output, format the output to be a proper list in English:

```python
repos = ['NCAR/xdev', 'NCAR/xdevbot', 'NCAR/something']
message = f"Some missing repositories include {', '.join(repr(i) for i in ll)}."
```

**Comment by kmpaul** [comment]
And similarly, something like this:

> because it doesn't exist in the list of repos: ['xarray-contrib/cf-xarray', 'NCAR/integral'] in the analysis campaign.

could be reformatted easily to read:

> because it doesn't exist in the list of repos ('xarray-contrib/cf-xarray', 'NCAR/integral') in the analysis campaign.
